basePath: /v1
host: localhost:8080
info:
  contact: {}
  title: Gollege
  version: "1.0"
paths:
  /enem/2019:
    get:
      description: Get question
      responses: {}
      summary: List questions
      tags:
      - ENEM
  /enem/2020:
    get:
      description: Get question
      responses: {}
      summary: List questions
      tags:
      - ENEM
  /enem/2021:
    get:
      description: Get question
      responses: {}
      summary: List questions
      tags:
      - ENEM
  /enem/2022:
    get:
      description: Get question
      responses: {}
      summary: List questions
      tags:
      - ENEM
  /enem/2023:
    get:
      description: Get question
      responses: {}
      summary: List questions
      tags:
      - ENEM
swagger: "2.0"
